# -*- coding: utf-8 -*-
"""AI Group Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ME3cQJH41mkY2dfOk8N0w0bOyH9Nh2hz
"""

# Install if needed (Google Colab)
!pip -q install kaggle tensorflow scikit-learn seaborn pillow

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))

"""## 1. Download the dataset

"""

#!/bin/bash
!kaggle datasets download grassknoted/asl-alphabet

# Step 2: Unzip the downloaded file
!unzip -q  asl-alphabet.zip

import os
import numpy as np
import tensorflow as tf
import cv2
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.vgg16 import preprocess_input

train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    "/content/asl_alphabet_train/asl_alphabet_train",
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    shuffle=True
)

"""## 2. Select only A–Z

The source dataset also contains `space`, `delete`, and `nothing`. They are excluded because the required output is a letter.
"""

DATA_ROOT = "/content/asl_alphabet_train/asl_alphabet_train"
letters = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")

available = [x for x in letters if os.path.isdir(os.path.join(DATA_ROOT, x))]
print("Number of letter classes:", len(available))
print("Available:", available)
assert len(available) == 26, "Check DATA_ROOT: A-Z folders were not found."

"""## 3. Load and preprocess images"""

import os
import tensorflow as tf
from sklearn.model_selection import train_test_split

IMG_SIZE = (128, 128)
BATCH_SIZE = 32
SEED = 42

DATA_ROOT = "/content/asl_alphabet_train/asl_alphabet_train"
letters = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")

all_image_paths = []
all_image_labels = []

label_to_index = {label: i for i, label in enumerate(letters)}

for letter in letters:
    letter_dir = os.path.join(DATA_ROOT, letter)
    if os.path.isdir(letter_dir):
        for fname in os.listdir(letter_dir):
            if fname.lower().endswith(('.png', '.jpg', '.jpeg')):
                all_image_paths.append(os.path.join(letter_dir, fname))
                all_image_labels.append(label_to_index[letter])

# Convert labels to one-hot encoding for categorical_crossentropy
all_image_labels_onehot = tf.keras.utils.to_categorical(all_image_labels, num_classes=len(letters))

# Stratified split using sklearn
X_train, X_val, y_train, y_val = train_test_split(
    all_image_paths, all_image_labels_onehot,
    test_size=0.20, random_state=SEED, stratify=all_image_labels)

# Function to load and preprocess images for tf.data.Dataset
def preprocess_image(image_path, label):
    image = tf.io.read_file(image_path)
    image = tf.image.decode_jpeg(image, channels=3) # Assuming JPEG, adjust if other formats
    image = tf.image.resize(image, IMG_SIZE)
    image = tf.cast(image, tf.float32) / 255.0 # Rescale to [0,1]
    return image, label

# Create tf.data.Dataset
train_ds = tf.data.Dataset.from_tensor_slices((X_train, y_train))
val_ds = tf.data.Dataset.from_tensor_slices((X_val, y_val))

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.map(preprocess_image, num_parallel_calls=AUTOTUNE) \
                   .shuffle(buffer_size=1024, seed=SEED) \
                   .batch(BATCH_SIZE) \
                   .prefetch(AUTOTUNE)

val_ds = val_ds.map(preprocess_image, num_parallel_calls=AUTOTUNE) \
                 .batch(BATCH_SIZE) \
                 .prefetch(AUTOTUNE)

class_names = np.array(letters) # Class names are now just the letters

data_augmentation = keras.Sequential([
    layers.RandomRotation(0.08),
    layers.RandomZoom(0.10),
    layers.RandomContrast(0.10)
], name="data_augmentation")

print("Number of training samples:", len(X_train))
print("Number of validation samples:", len(X_val))
print("Class names:", class_names)

"""## 4. View sample images"""

plt.figure(figsize=(10, 8))
for images, labels in train_ds.take(1):
    for i in range(12):
        ax = plt.subplot(3, 4, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(class_names[np.argmax(labels[i].numpy())])
        plt.axis("off")
plt.tight_layout()
plt.show()

"""## 5. Build the CNN



"""

model = keras.Sequential([
    layers.Input(shape=(128, 128, 3)),
    data_augmentation,
    layers.Rescaling(1./255),

    layers.Conv2D(32, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(128, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.40),
    layers.Dense(26, activation="softmax")
])

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss="categorical_crossentropy",
    metrics=["accuracy"])

model.summary()

"""## 6. Train the CNN"""

callbacks = [
    keras.callbacks.EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True),
    keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=2, min_lr=1e-6)
]

history = model.fit(
    train_ds, validation_data=val_ds,
    epochs=15, callbacks=callbacks)

"""## 7. Training curves"""

plt.figure(figsize=(8, 5))
plt.plot(history.history["accuracy"], label="Training Accuracy")
plt.plot(history.history["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epoch"); plt.ylabel("Accuracy"); plt.title("CNN Accuracy")
plt.legend(); plt.show()

plt.figure(figsize=(8, 5))
plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")
plt.xlabel("Epoch"); plt.ylabel("Loss"); plt.title("CNN Loss")
plt.legend(); plt.show()

"""## 8. Evaluate the model"""

val_loss, val_accuracy = model.evaluate(val_ds, verbose=1)
print(f"Validation accuracy: {val_accuracy:.4f}")
print(f"Validation loss: {val_loss:.4f}")

y_true, y_pred = [], []
for images, labels in val_ds:
    probabilities = model.predict(images, verbose=0)
    y_true.extend(np.argmax(labels.numpy(), axis=1))
    y_pred.extend(np.argmax(probabilities, axis=1))

print(classification_report(y_true, y_pred, labels=np.arange(len(class_names)), target_names=class_names, digits=4))

"""## 9. Confusion matrix"""

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(14, 12))
sns.heatmap(cm, annot=True, fmt="d", xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicted Letter"); plt.ylabel("True Letter")
plt.title("ASL Letter Recognition — Confusion Matrix")
plt.show()

"""## 10. Predict a single ASL image

This is the main feature: **image in → predicted letter out**.
"""

from PIL import Image

def predict_asl_letter(image_path):
    image = Image.open(image_path).convert("RGB").resize(IMG_SIZE)
    image_array = np.expand_dims(np.array(image).astype("float32"), axis=0)

    probabilities = model.predict(image_array, verbose=0)[0]
    index = np.argmax(probabilities)
    letter = class_names[index]
    confidence = probabilities[index] * 100

    plt.figure(figsize=(4, 4))
    plt.imshow(image)
    plt.title(f"Predicted Letter: {letter}\nConfidence: {confidence:.2f}%")
    plt.axis("off")
    plt.show()

    return letter, confidence

from google.colab import files

# Upload an ASL image
uploaded = files.upload()
image_path = next(iter(uploaded.keys()))

letter, confidence = predict_asl_letter(image_path)
print(f"Predicted Letter: {letter}")
print(f"Confidence: {confidence:.2f}%")

"""## 11. Save the trained CNN

"""

model.save("/content/asl_cnn_model.keras")
print("Saved: /content/asl_cnn_model.keras")

"""## Conclusion

This project performs **static ASL alphabet image classification** for 26 letters.

Example:

**Input:** ASL image showing B  
**Output:** `Predicted Letter: B`

**Limitation:** Real ASL recognition is more complex than static image classification. In particular, J and Z involve motion in real fingerspelling; this project classifies the static examples provided by the dataset.
"""